### ISSUE TITLE
Write System / Integration tests for API vertical slice

### ISSUE THREAD

**Issue by epage** [ni/nixnet-python#25]
This is a tracking issue for the system and integration tests that created. 

- [x] Test per session type
- [x] Basic session properties
- [x] Start and stop

There is always the opportunity to test more but there is a long tail to it.  All new functions will have tests written for them.  It'll just be the slow catch up to get all the properties (and session flush and wait).

See #88 

Blocked on
- [x] #23  an API to test
